@startuml "CM1_7 - Вычислить собственные числа"

actor "Пользователь" as User

usecase "Просмотреть результаты расчета" as CM1_7_1
usecase "Вернуться к когнитивной карте" as CM1_7_2

User -up-> CM1_7_1
User -up-> CM1_7_2



@enduml
