@startuml "FW1_6 - Навигация по приложению"

actor "Пользователь" as User


usecase "Главный экран" as FW1_6_1
usecase "Экран редактирования факторов" as FW1_6_2
usecase "Форма добавления фактора" as FW1_6_3
usecase "Экран редактирования когнитивной карты" as FW1_6_4
usecase "Экран анализа динамики" as FW1_6_5



User <-up-> FW1_6_1
FW1_6_1 <-up-> FW1_6_2
FW1_6_1 <-up-> FW1_6_4
FW1_6_4 <-down-> FW1_6_3
FW1_6_4 <-down-> FW1_6_2
FW1_6_4 <-down-> FW1_6_5



@enduml
